development: &defaults
  adapter: postgresql
  encoding: utf8
  database: newapp
  username: postgres
  password: root
  host: localhost
  pool: 5
  timeout: 5000

production:
  url:

test:
  <<: *defaults
  host: localhost
  username: postgres
  database: newapp_test
