development: &defaults
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: 5
  timeout: 5000

production:
  url:

test:
  <<: *defaults
  host: <%= ENV['DATABASE_HOST_TEST'] %>
  username: <%= ENV['DATABASE_USERNAME_TEST'] %>
  database: <%= ENV['DATABASE_NAME_TEST'] %>
