development: &defaults
  adapter: postgresql
  encoding: utf8
  database: newapp
  username: postgres
  password: root
  host: localhost
  pool: 5
  timeout: 5000

production:
  url:

test:
  <<: *defaults
  host: <%= ENV['DATABASE_HOST_TEST'] %>
  username: <%= ENV['DATABASE_USERNAME_TEST'] %>
  database: <%= ENV['DATABASE_NAME_TEST'] %>
